version: "3"
services:
  keycloak:
    build: ./keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
    ports:
      - "8080:8080"
    command:
      - start-dev
    develop:
      watch:
        - action: rebuild
          path: ./keycloak
  keycloak-config-cli:
    build: ./config
    volumes:
      - ./config/src:/config
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: true
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 120s
      IMPORT_FILES_LOCATIONS: /config/*
      IMPORT_CACHE_ENABLED: false
      IMPORT_VARSUBSTITUTION_ENABLED: true
    env_file:
      - path: .env
        required: false
    restart: "no"
    develop:
      watch:
        - action: sync+restart
          path: ./config/src
          target: /config
