version: "3"
services:
  keycloak:
    build: 
      context: ./keycloak
      args:
        KEYCLOAK_VERSION: 26.1.3
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
    ports:
      - 8080:8080
    command:
      - start
      - --optimized
      - --http-enabled
      - 'true'
      - --hostname-strict
      - 'false'
    develop:
      watch:
        - action: rebuild
          path: ./keycloak

  keycloak-config-cli:
    build:
      context: ./keycloak-config-cli
      args:
        KEYCLOAK_CONFIG_CLI_VERSION: latest
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: true
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 120s
      IMPORT_FILES_LOCATIONS: /config/*
      IMPORT_CACHE_ENABLED: false
      IMPORT_VARSUBSTITUTION_ENABLED: true
      # Mock secrets
      GRAFANA_CLIENT_SECRET: mock_grafana_client_secret
      GRAFANA_CLIENT_URL: http://localhost:3000
      CILOGON_CLIENT_ID: abc13
      CILOGON_CLIENT_SECRET: abc123

    env_file:
      - path: .env
        required: false
    restart: "no"
    develop:
      watch:
        - action: sync+restart
          path: ./keycloak-config-cli/config
          target: /config
  grafana:
    profiles:
      - grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN: "false"
      GF_AUTH_GENERIC_OAUTH_NAME: "VEDA Keycloak"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      # Role Mapping
      GF_AUTH_GENERIC_OAUTH_AUTO_ASSIGN_ORG_ROLE: Admin
      # Auth server details
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: grafana
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: mock_grafana_client_secret
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: http://localhost:8080/realms/veda/protocol/openid-connect/auth
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: http://keycloak:8080/realms/veda/protocol/openid-connect/token
      GF_AUTH_GENERIC_OAUTH_API_URL: http://keycloak:8080/realms/veda/protocol/openid-connect/userinfo
