[project]
name = "veda-keycloak"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aws-cdk-lib>=2.181.1",
    "pydantic-settings>=2.8.1",
    "pyyaml>=6.0.2",
]
