---
enabled: true
realm: master
displayName: Admin
displayNameHtml: VEDA Keycloak Admin

loginTheme: veda
loginWithEmailAllowed: false

identityProviders:
  # GitHub with Org Check
  - alias: github-org-check # NOTE: this alias appears in the redirect_uri for the auth flow, update Github OAuth settings accordingly
    displayName: GitHub [NASA-IMPACT]
    providerId: github-org
    enabled: true
    updateProfileFirstLoginMode: on
    trustEmail: false
    storeToken: false
    addReadTokenRoleOnCreate: false
    authenticateByDefault: false
    linkOnly: false
    config:
      clientId: $(env:GH_CLIENT_ID)
      clientSecret: $(env:GH_CLIENT_SECRET)
      defaultScope: openid read:org user:email
      organization: developmentseed
      team: $(env:GH_ADMIN_TEAM:-"veda-auth")
      caseSensitiveOriginalUsername: "false"
      syncMode: FORCE

identityProviderMappers:
  # If a user logs in with the github-org-check provider, they will be assigned the "admin" role
  - name: Auto admin
    identityProviderAlias: github-org-check
    identityProviderMapper: oidc-hardcoded-role-idp-mapper
    config:
      syncMode: FORCE
      role: admin


# Login Flow Configuration
browserFlow: Browser without Password
authenticationFlows:
  - alias: Browser without Password
    description: browser based authentication without username password form
    providerId: basic-flow
    topLevel: true
    builtIn: false
    authenticationExecutions:
      - authenticator: auth-cookie
        authenticatorFlow: false
        requirement: ALTERNATIVE
        priority: 10
        autheticatorFlow: false
        userSetupAllowed: false
      - authenticator: auth-spnego
        authenticatorFlow: false
        requirement: DISABLED
        priority: 20
        autheticatorFlow: false
        userSetupAllowed: false
      - authenticatorFlow: true
        requirement: ALTERNATIVE
        priority: 30
        autheticatorFlow: true
        flowAlias: Browser without Password forms
        userSetupAllowed: false
  - alias: Browser without Password forms
    description: Username, password, otp and other auth forms.
    providerId: basic-flow
    topLevel: false
    builtIn: false
    authenticationExecutions:
      - authenticatorConfig: github-org-check
        authenticator: identity-provider-redirector
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 20
        autheticatorFlow: false
        userSetupAllowed: false
      - authenticatorFlow: true
        requirement: CONDITIONAL
        priority: 21
        autheticatorFlow: true
        flowAlias: Browser without Password Browser - Conditional OTP
        userSetupAllowed: false
  - alias: Browser without Password Browser - Conditional OTP
    description: Flow to determine if the OTP is required for the authentication
    providerId: basic-flow
    topLevel: false
    builtIn: false
    authenticationExecutions:
      - authenticator: conditional-user-configured
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 10
        autheticatorFlow: false
        userSetupAllowed: false
      - authenticator: auth-otp-form
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 20
        autheticatorFlow: false
        userSetupAllowed: false
authenticatorConfig:
  - alias: github-org-check
    config:
      defaultProvider: github-org-check
