$schema: "http://json-schema.org/draft-07/schema#"
type: object
properties:
  id:
    type: string
  clients:
    type: array
    items:
      type: object
      properties:
        clientId:
          type: string
        name:
          type: string
        rootUrl:
          type: string
        baseUrl:
          type: string
        enabled:
          type: boolean
        attributes:
          type: object
        redirectUris:
          type: array
          items:
            type: string
        webOrigins:
          type: array
          items:
            type: string
        protocol:
          type: string
        fullScopeAllowed:
          type: boolean
  realm:
    type: string
  displayName:
    type: string
  internationalizationEnabled:
    type: boolean
  supportedLocales:
    type: array
    items:
      type: string
  authenticationFlows:
    type: array
    items:
      type: object
      properties:
        alias:
          type: string
        description:
          type: string
        providerId:
          type: string
        topLevel:
          type: boolean
        builtIn:
          type: boolean
        authenticationExecutions:
          type: array
          items:
            type: object
            properties:
              authenticator:
                type: string
              authenticatorConfig:
                type: string
              requirement:
                type: string
                enum: ["REQUIRED", "ALTERNATIVE", "DISABLED"]
              priority:
                type: integer
              userSetupAllowed:
                type: boolean
              authenticatorFlow:
                type: boolean
            required:
              - authenticator
              - requirement
              - priority
      required:
        - alias
        - providerId
        - topLevel
        - builtIn
  roles:
    type: object
    properties:
      realm:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            composite:
              type: boolean
            clientRole:
              type: boolean
          required: ["name"]
      client:
        type: object
        additionalProperties:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              composite:
                type: boolean
              clientRole:
                type: boolean
            required: ["name"]
  groups:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        path:
          type: string
        subGroups:
          type: array
          items:
            type: object
        attributes:
          type: object
        realmRoles:
          type: array
          items:
            type: string
        clientRoles:
          type: object
  scopeMappings:
    type: array
    items:
      type: object
      properties:
        clientScope:
          type: string
        roles:
          type: array
          items:
            type: string
      required: ["clientScope", "roles"]
  users:
    type: array
    items:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        enabled:
          type: boolean
        firstName:
          type: string
        lastName:
          type: string
        realmRoles:
          type: array
          items:
            type: string
        clientRoles:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        credentials:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              value:
                type: string
            required: ["type", "value"]
      required: ["username", "enabled", "credentials"]
# required:
#   # - id
#   - realm
#   # - displayName
#   # - authenticationFlows