---
enabled: true
realm: master
displayName: VEDA Master Realm
displayNameHtml: VEDA Master Realm

loginTheme: veda
loginWithEmailAllowed: false

identityProviders:
  # GitHub with Org Check
  - alias: github-org-check # NOTE: this alias appears in the redirect_uri for the auth flow, update Github OAuth settings accordingly
    displayName: GitHub [NASA-IMPACT]
    providerId: github-org
    enabled: true
    updateProfileFirstLoginMode: on
    trustEmail: false
    storeToken: false
    addReadTokenRoleOnCreate: false
    authenticateByDefault: false
    linkOnly: false
    config:
      clientId: $(env:GH_CLIENT_ID)
      clientSecret: $(env:GH_CLIENT_SECRET)
      defaultScope: openid read:org user:email
      organization: nasa-impact
      caseSensitiveOriginalUsername: "false"
      syncMode: FORCE

identityProviderMappers:
  # If a user logs in with the github-org-check provider, they will be assigned the "admin" role
  - name: Auto admin
    identityProviderAlias: github-org-check
    identityProviderMapper: oidc-hardcoded-role-idp-mapper
    config:
      syncMode: FORCE
      role: admin
