---
enabled: true
realm: veda
displayName: Applications
displayNameHtml: VEDA Ecosystem

clients:
  - clientId: grafana
    name: Grafana
    rootUrl: $(env:GRAFANA_CLIENT_URL:-https://grafana-keycloak.delta-backend.xyz)
    secret: $(env:GRAFANA_CLIENT_SECRET)
    publicClient: false
    attributes: {}
    redirectUris:
      - $(env:GRAFANA_CLIENT_URL:-https://grafana-keycloak.delta-backend.xyz)/*
    webOrigins:
      - $(env:GRAFANA_CLIENT_URL:-https://grafana-keycloak.delta-backend.xyz)
    protocol: openid-connect
    fullScopeAllowed: true
    defaultClientScopes:
      - web-origins
      - acr
      - profile
      - roles
      - basic
      - email
      - grafana:admin
      - grafana:editor
      - grafana:viewer

roles:
  client:
    grafana:
      - name: Administrator
        description: Grafana Administrator
      - name: Editor
        description: Grafana Editor
      - name: Viewer
        description: Grafana Viewer

clientScopeMappings:
  grafana:
    - clientScope: grafana:admin
      roles:
        - Administrator
    - clientScope: grafana:editor
      roles:
        - Editor
    - clientScope: grafana:viewer
      roles:
        - Viewer

clientScopes:
  # Grafana
  - name: grafana:admin
    description: Admin access to Grafana
    protocol: openid-connect
  - name: grafana:editor
    description: Editor access to Grafana
    protocol: openid-connect
  - name: grafana:viewer
    description: Viewer access to Grafana
    protocol: openid-connect

groups:
  - name: System Administrators
    clientRoles:
      grafana:
        - Administrator

  - name: Developers
    clientRoles:
      grafana:
        - Editor

  - name: Data Editors
    clientRoles:
      grafana:
        - Viewer

identityProviders:
  # CILogon
  - alias: cilogon # NOTE: this alias appears in the redirect_uri for the auth flow, update Github OAuth settings accordingly
    displayName: CILogon
    providerId: oidc
    enabled: true
    updateProfileFirstLoginMode: on
    trustEmail: false
    storeToken: false
    addReadTokenRoleOnCreate: false
    authenticateByDefault: false
    linkOnly: false
    config:
      userInfoUrl: "https://cilogon.org/oauth2/userinfo"
      validateSignature: "true"
      tokenUrl: "https://cilogon.org/oauth2/token"
      jwksUrl: "https://cilogon.org/oauth2/certs"
      issuer: "https://cilogon.org"
      useJwksUrl: "true"
      pkceEnabled: "false"
      metadataDescriptorUrl: "https://cilogon.org/.well-known/openid-configuration"
      authorizationUrl: "https://cilogon.org/authorize"
      clientAuthMethod: "client_secret_post"
      syncMode: "LEGACY"
      clientId: $(env:CILOGON_CLIENT_ID)
      clientSecret: $(env:CILOGON_CLIENT_SECRET)

# Login Flow Configuration
browserFlow: Browser without Password
authenticationFlows:
  - alias: Browser without Password
    description: browser based authentication without username password form
    providerId: basic-flow
    topLevel: true
    builtIn: false
    authenticationExecutions:
      - authenticator: auth-cookie
        authenticatorFlow: false
        requirement: ALTERNATIVE
        priority: 10
        autheticatorFlow: false
        userSetupAllowed: false
      - authenticator: auth-spnego
        authenticatorFlow: false
        requirement: DISABLED
        priority: 20
        autheticatorFlow: false
        userSetupAllowed: false
      - authenticatorFlow: true
        requirement: ALTERNATIVE
        priority: 30
        autheticatorFlow: true
        flowAlias: Browser without Password forms
        userSetupAllowed: false
  - alias: Browser without Password forms
    description: Username, password, otp and other auth forms.
    providerId: basic-flow
    topLevel: false
    builtIn: false
    authenticationExecutions:
      - authenticatorConfig: cilogon
        authenticator: identity-provider-redirector
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 20
        autheticatorFlow: false
        userSetupAllowed: false
      - authenticatorConfig: check-idp
        authenticator: conditional-user-attribute
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 1
        autheticatorFlow: false
        userSetupAllowed: false
      - authenticatorFlow: true
        requirement: CONDITIONAL
        priority: 21
        autheticatorFlow: true
        flowAlias: Browser without Password Browser - Conditional OTP
        userSetupAllowed: false
  - alias: Browser without Password Browser - Conditional OTP
    description: Flow to determine if the OTP is required for the authentication
    providerId: basic-flow
    topLevel: false
    builtIn: false
    authenticationExecutions:
      - authenticator: conditional-user-configured
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 10
        autheticatorFlow: false
        userSetupAllowed: false
      - authenticator: auth-otp-form
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 20
        autheticatorFlow: false
        userSetupAllowed: false
authenticatorConfig:
  - alias: check-idp
    config:
      attribute_expected_value: Google##GitHub  # Permitted IDPs
      attribute_name: idp_display_name
  - alias: cilogon
    config:
      defaultProvider: cilogon
