---
enabled: true
realm: ghgc
displayName: Applications
displayNameHtml: GHGC 

clients:
  - clientId: ghgc-stac
    name: GHGC STAC Catalog
    rootUrl: https://dev.ghg.center/api/stac
    publicClient: true
    attributes: {}
    redirectUris:
      - https://dev.ghg.center/api/stac/*
    webOrigins:
      - https://dev.ghg.center/api/stac
    protocol: openid-connect
    fullScopeAllowed: true
    defaultClientScopes:
      - web-origins
      - acr
      - profile
      - roles
      - basic
      - email
      - stac:item:create
      - stac:item:update
      - stac:item:delete
      - stac:collection:create
      - stac:collection:update
      - stac:collection:delete

  - clientId: ghgc-airflow-stac-etl
    name: GHGC Airflow STAC ETL
    secret: $(env:GHGC_AIRFLOW_STAC_ETL_CLIENT_SECRET)
    publicClient: false
    attributes: {}
    protocol: openid-connect
    fullScopeAllowed: true
    standardFlowEnabled: false
    implicitFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: true
    optionalClientScopes:
      - stac:item:create
      - stac:item:update
      - stac:item:delete
      - stac:collection:create
      - stac:collection:update
      - stac:collection:delete
    defaultClientScopes:
      - roles
  
  - clientId: ghgc-ingest-api
    name: GHGC Ingest API
    rootUrl: https://dev.ghg.center/api/ingest
    publicClient: true
    attributes: {}
    redirectUris:
      - https://dev.ghg.center/api/ingest/*
      - https://staging.earth.gov/ghgcenter/api/ingest/*
    webOrigins:
      - https://dev.ghg.center
      - https://staging.earth.gov
    protocol: openid-connect
    fullScopeAllowed: true
    defaultClientScopes:
      - web-origins
      - acr
      - profile
      - roles
      - basic
      - email
      - stac:item:create
      - stac:item:update
      - stac:item:delete
      - stac:collection:create
      - stac:collection:update
      - stac:collection:delete

  - clientId: ghgc-airflow-ingest-api-etl
    name: GHGC Airflow Ingest API ETL
    secret: $(env:GHGC_AIRFLOW_INGEST_API_ETL_CLIENT_SECRET)
    publicClient: false
    attributes: {}
    protocol: openid-connect
    fullScopeAllowed: true
    standardFlowEnabled: false
    implicitFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: true
    optionalClientScopes:
      - stac:item:create
      - stac:item:update
      - stac:item:delete
      - stac:collection:create
      - stac:collection:update
      - stac:collection:delete
    defaultClientScopes:
      - roles

  - clientId: airflow-webserver-fab
    name: Airflow Webserver FAB
    rootUrl: https://sm2a.dev.ghg.center/
    publicClient: false
    secret: $(env:AIRFLOW_WEBSERVER_FAB_CLIENT_SECRET)
    attributes:
      realm_client: "false"
      oidc.ciba.grant.enabled: "false"
      backchannel.logout.session.required: "true"
      standard.token.exchange.enabled: "false"
      oauth2.device.authorization.grant.enabled: "false"
      backchannel.logout.revoke.offline.tokens: "false"
    redirectUris:
      - https://sm2a.dev.ghg.center/oauth-authorized/keycloak
      - https://sm2a.staging.earth.gov/oauth-authorized/keycloak
    webOrigins:
      - https://sm2a.dev.ghg.center
      - https://sm2a.staging.earth.gov
    protocol: openid-connect
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: true
    fullScopeAllowed: true
    frontchannelLogout: true
    defaultClientScopes:
      - web-origins
      - acr
      - profile
      - roles
      - basic
      - email
    
roles:
  client:
    ghgc-stac:
      - name: Admin
        description: Can create, update and delete STAC collections and items
      - name: Editor
        description: Can create and update STAC collections and items
      - name: Viewer
        description: Can only view STAC collections and items
    ghgc-ingest-api:
      - name: Admin
        description: Can create, update and delete STAC collections and items
      - name: Editor
        description: Can create and update STAC collections and items
      - name: No Basic Role
        description: Has no permissions
    airflow-webserver-fab:
      - name: Admin
        description: Has all possible permissions, including granting or revoking permissions from other users
      - name: Public
        description: No permissions
      - name: Viewer
        description: Limited read permissions
      - name: User
        description: Viewer permissions plus additional permissions
      - name: Dag_Launcher
        description: Programmatic DAG runs

clientScopeMappings:
  ghgc-stac:
    - clientScope: stac:item:create
      roles:
        - Admin
        - Editor
    - clientScope: stac:item:update
      roles:
        - Admin
        - Editor
    - clientScope: stac:item:delete
      roles:
        - Admin
        - Editor
    - clientScope: stac:collection:create
      roles:
        - Admin
        - Editor
    - clientScope: stac:collection:update
      roles:
        - Admin
        - Editor
    - clientScope: stac:collection:delete
      roles:
        - Admin
  ghgc-ingest-api:
    - clientScope: stac:item:create
      roles:
        - Admin
        - Editor
    - clientScope: stac:item:update
      roles:
        - Admin
        - Editor
    - clientScope: stac:item:delete
      roles:
        - Admin
        - Editor
    - clientScope: stac:collection:create
      roles:
        - Admin
        - Editor
    - clientScope: stac:collection:update
      roles:
        - Admin
        - Editor
    - clientScope: stac:collection:delete
      roles:
        - Admin

clientScopes:
  - name: stac:item:create
    description: Create STAC items
    protocol: openid-connect
  - name: stac:item:update
    description: Update STAC items
    protocol: openid-connect
  - name: stac:item:delete
    description: Delete STAC items
    protocol: openid-connect
  - name: stac:collection:create
    description: Create STAC collections
    protocol: openid-connect
  - name: stac:collection:update
    description: Update STAC collections
    protocol: openid-connect
  - name: stac:collection:delete
    description: Delete STAC collections
    protocol: openid-connect

groups:
  - name: System Administrators
    clientRoles:
      ghgc-stac:
        - Admin
      ghgc-ingest-api:
        - Admin
      airflow-webserver-fab:
        - Admin

  - name: Developers
    clientRoles:
      ghgc-stac:
        - Admin
      ghgc-ingest-api:
        - Admin
      airflow-webserver-fab:
        - User

  - name: Data Editors
    clientRoles:
      ghgc-stac:
        - Editor
      ghgc-ingest-api:
        - Editor
      airflow-webserver-fab:
        - User

  - name: No Basic Role
    clientRoles:
      ghgc-stac:
        - Viewer
      ghgc-ingest-api:
        - No Basic Role
      airflow-webserver-fab:
        - Public

identityProviders:
  # CILogon
  - alias: cilogon # NOTE: this alias appears in the redirect_uri for the auth flow, update Github OAuth settings accordingly
    displayName: CILogon
    providerId: oidc
    enabled: true
    updateProfileFirstLoginMode: on
    trustEmail: false
    storeToken: false
    addReadTokenRoleOnCreate: false
    authenticateByDefault: false
    linkOnly: false
    config:
      userInfoUrl: "https://cilogon.org/oauth2/userinfo"
      validateSignature: "true"
      tokenUrl: "https://cilogon.org/oauth2/token"
      jwksUrl: "https://cilogon.org/oauth2/certs"
      issuer: "https://cilogon.org"
      useJwksUrl: "true"
      pkceEnabled: "false"
      defaultScope: "openid email profile"
      metadataDescriptorUrl: "https://cilogon.org/.well-known/openid-configuration"
      authorizationUrl: "https://cilogon.org/authorize"
      clientAuthMethod: "client_secret_post"
      syncMode: "IMPORT"
      clientId: $(env:CILOGON_CLIENT_ID)
      clientSecret: $(env:CILOGON_CLIENT_SECRET)
identityProviderMappers:
  - name: "email"
    identityProviderAlias: cilogon
    identityProviderMapper: oidc-user-attribute-idp-mapper
    config:
      syncMode: "IMPORT"
      claim: "email"
      user.attribute: "email"
  - name: "first name"
    identityProviderAlias: cilogon
    identityProviderMapper: oidc-user-attribute-idp-mapper
    config:
      syncMode: "IMPORT"
      claim: "profile.given_name"
      user.attribute: "firstName"
  - name: "last name"
    identityProviderAlias: cilogon
    identityProviderMapper: oidc-user-attribute-idp-mapper
    config:
      syncMode: "IMPORT"
      claim: "profile.family_name"
      user.attribute: "lastName"

authenticatorConfig:
  - alias: cilogon
    config:
      defaultProvider: cilogon

users:
  - username: service-account-airflow-webserver-fab
    emailVerified: true
    enabled: true
    serviceAccountClientId: airflow-webserver-fab
    clientRoles:
      airflow-webserver-fab:
      - Dag_Launcher
  - username: service-account-airflow-stac-etl
    emailVerified: true
    enabled: true
    serviceAccountClientId: ghgc-airflow-stac-etl
    clientRoles:
      ghgc-stac:
      - Admin
  - username: service-account-airflow-ingest-api-etl
    emailVerified: true
    enabled: true
    serviceAccountClientId: ghgc-airflow-ingest-api-etl
    clientRoles:
      ghgc-ingest-api:
      - Admin

defaultGroups:
  - "/No Basic Role"
