name: Diff CDK Stack

on:
  pull_request:

run-name: Diff ${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read

    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Setup UV
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0

      - name: Install dependencies
        run: |
          uv sync --locked

      - name: Run pre-commit
        run: |
          uv run pre-commit run --all-files
  diff:
    runs-on: ubuntu-latest
    environment: dev
    needs: [lint]
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c #v6.2.3
        with:
          role-to-assume: ${{ vars.AWS_CDK_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: GitHubActionsCDKDeploy
          role-duration-seconds: 3600

      - uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0

      - name: Install dependencies
        run: uv sync --locked

      - name: Synthesize CDK
        run: uv run npx cdk synth
        env:
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          CDK_BOOTSTRAP_QUALIFIER: ${{ vars.CDK_BOOTSTRAP_QUALIFIER }}
          VPC_ID: ${{ vars.VPC_ID }}
          PERMISSIONS_BOUNDARY_ARN: ${{ vars.PERMISSIONS_BOUNDARY_ARN }}
          HOSTNAME: ${{ vars.HOSTNAME }}
          KEYCLOAK_VERSION: ${{ vars.KEYCLOAK_VERSION }}
          KEYCLOAK_CONFIG_CLI_VERSION: ${{ vars.KEYCLOAK_CONFIG_CLI_VERSION }}
          SSL_CERTIFICATE_ARN: ${{ vars.SSL_CERTIFICATE_ARN }}
          RDS_SNAPSHOT_IDENTIFIER: ${{ vars.RDS_SNAPSHOT_IDENTIFIER }}
          STAGE: dev
          CONFIGURE_ROUTE53: ${{ vars.CONFIGURE_ROUTE53 }}
          # Imported Identity Provider secrets
          IDP_SECRET_ARN_GH: ${{ vars.IDP_SECRET_ARN_GH }}
          IDP_SECRET_ARN_CILOGON: ${{ vars.IDP_SECRET_ARN_CILOGON }}
          IDP_SECRET_ARN_EDL: ${{ vars.IDP_SECRET_ARN_EDL }}
          KEYCLOAK_SEND_EMAIL_ADDRESS_VEDA: ${{ vars.KEYCLOAK_SEND_EMAIL_ADDRESS_VEDA }}
          KEYCLOAK_SEND_EMAIL_ADDRESS_MAAP: ${{ vars.KEYCLOAK_SEND_EMAIL_ADDRESS_MAAP }}
          APPLICATION_ROLE_ARN_AIRFLOW_INGEST_API_ETL: ${{ vars.APPLICATION_ROLE_ARN_AIRFLOW_INGEST_API_ETL }}
          APPLICATION_ROLE_ARN_DISASTERS_AIRFLOW_INGEST_API_ETL: ${{ vars.APPLICATION_ROLE_ARN_DISASTERS_AIRFLOW_INGEST_API_ETL }}
          APPLICATION_ROLE_ARN_EIC_AIRFLOW_INGEST_API_ETL: ${{ vars.APPLICATION_ROLE_ARN_EIC_AIRFLOW_INGEST_API_ETL }}
          APPLICATION_ROLE_ARN_EIC_UMA_RESOURCE_SERVER: ${{ vars.APPLICATION_ROLE_ARN_EIC_UMA_RESOURCE_SERVER }}
          APPLICATION_ROLE_ARN_GHGC_AIRFLOW_WEBSERVER_FAB: ${{ vars.APPLICATION_ROLE_ARN_GHGC_AIRFLOW_WEBSERVER_FAB }}
          APPLICATION_ROLE_ARN_GHGC_AIRFLOW_INGEST_API_ETL: ${{ vars.APPLICATION_ROLE_ARN_GHGC_AIRFLOW_INGEST_API_ETL }}
      - name: Diff CDK
        uses: corymhall/cdk-diff-action@ad67041313333f7f2bd26b33f18fb134610a971e # v2.0.9
        with:
          failOnDestructiveChanges: false
          githubToken: ${{ secrets.GITHUB_TOKEN }}
